server:
  port: 8080
spring:
  datasource:
    username: root
    password: P@ssw0rd
    url: jdbc:mysql://139.199.67.139:3306/it_yun_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lx.spring_boot_learn.entity